#!/usr/bin/env bash
# This script configures a server to get the Nginx running and listening on Port 80
sed -i "s/8080/80/g" /etc/nginx/sites-enabled/default
service nginx restart
kill -9 "$(cat /run/nginx.pid)"
