#!/usr/bin/env bash
# This script will display the phrase "Best School" 10 times but print Hi on the 9th time

i=0

while ((i < 10))
do
echo "Best School"
((i++))
if [ $i -eq 9 ]
then
echo "Hi"
fi
done
