#!/usr/bin/env bash
# This script will display the phrase "Best School" 10 times but print Hi on the 8th time

i=0

while ((i < 10))
do
((i++))
if [ $i -eq 4 ]
then
echo "bad luck"
elif [ $i -eq 8 ]
then
echo "good luck"
else
echo "Best School"
fi
done
