#!/usr/bin/env bash
# This is a script which installs the ufw firewall and sets up a few rules 
sudo ufw default deny incoming
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw disable
sudo ufw enable